<a href="https://colab.research.google.com/github/19PA1A0265/AI-Lab/blob/master/Experiment1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1) Experiment 1 : Numpy

## i) Different ways to create numpy arrays 

### a) Create a numpy array using list

In [ ]:
import numpy as np
a = np.array([2,6,9])
print (a)

[2 6 9]


In [ ]:
a = np.array([[1,2],[3,4]])
print (a)

[[1 2]
 [3 4]]


### b) Create a numpy array using arange

In [ ]:
a = np.arange(4)
print(a)

[0 1 2 3]


## ii) Add,remove,modify elements in an array

### a) Add

In [ ]:
newArray = np.append(a,[44,36,48]) 
print(newArray)

[ 1  2  3  4 44 36 48]


### b) Remove

In [ ]:
 
import numpy as np
l=np.array([4,6,9,3,7])
l=np.delete(l,4)
print(l)

[4 6 9 3]


### c) Modify

In [ ]:
 
b=np.array([9,6,4,1,8,5])
b[b<2]=-1
print(b)

[ 9  6  4 -1  8  5]


 ## iii) Arthimetic operations on Numpy array

In [ ]:
 
import numpy as np
v=np.random.random((8,8))
n=np.random.random((8,8))
sum=np.add(v,n)
diff=np.subtract(v,n)
prod=np.multiply(v,n)
quo=np.divide(v,n)
mod=np.mod(v,n)
pow=np.power(v,n)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[1.65416941 1.02014329 1.6699653  1.22142155 1.22740579 0.7081954
  0.83472589 0.11445453]
 [1.5658738  0.45953542 1.00736922 0.43364518 1.58195237 1.52058797
  1.17836289 1.15598948]
 [0.6981489  1.53569092 1.12819745 0.79300266 1.25962591 1.27004003
  1.18337963 0.67963199]
 [0.36842837 0.93239807 1.1556704  0.61087698 0.89012754 1.41564547
  0.88202906 0.61470712]
 [0.55295275 1.22778565 1.4057458  1.1953915  0.74832951 1.22921342
  0.69457828 0.69390851]
 [0.63013146 0.94943261 0.59178581 1.39835056 0.8816722  1.64723624
  1.07574925 0.93414687]
 [0.98463468 0.82007826 0.6285085  0.90526662 0.71135329 0.77734536
  0.88044376 0.55603836]
 [0.92158816 1.09971894 1.64178998 0.88349353 1.2055143  1.83031008
  0.85040079 0.95431191]]
[[-0.06278115 -0.68616578  0.23062716 -0.636601    0.13130495  0.05554758
  -0.81219265 -0.0881527 ]
 [-0.1321636  -0.32286296 -0.37113862  0.11780962  0.38247973 -0.2519502
   0.81672197  0.36508523]
 [ 0.46787643 -0.1127883   0.37634127 -0.74591856 -0.45

 ## iv) Slicing and iterating of numpy arrays

 ### a) Slicing

In [ ]:
import numpy as np
arr = np.array([4,5,6,8,9,7])
print(arr[2:6])

[6 8 9 7]


### b) Iterating

In [ ]:
for i in arr:
  print(i)

4
5
6
8
9
7


 ## V) Matrix operation on numpy arrays

In [ ]:
 
import numpy as np
v=np.array([[5,9],[4,3]])
i=np.array([[2,16],[1,12]])
print(np.add(v,i))
print(np.subtract(v,i))
print(np.divide(v,i))

[[ 7 25]
 [ 5 15]]
[[ 3 -7]
 [ 3 -9]]
[[2.5    0.5625]
 [4.     0.25  ]]
